# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
random_vector = torch.randn([7,7])
random_vector

tensor([[-0.3345,  1.4879,  0.5192, -1.9232, -0.9207, -2.1089,  0.8988],
        [ 0.8340, -1.0674,  0.5642, -1.6431,  0.9133,  0.4312, -0.3434],
        [-0.6097, -0.1775,  1.7214, -0.4730,  1.1196,  0.2716,  0.6232],
        [-0.0745,  1.6481, -0.6438, -0.1653, -0.2253,  0.3386, -1.6591],
        [ 0.4123, -0.4649,  0.3751,  0.4527,  1.8631,  0.0476, -1.3657],
        [ 0.5959, -0.1816, -0.0101, -1.2540,  0.6933,  0.9086, -0.2874],
        [ 0.0216, -1.2996,  0.4479, -1.2324,  0.5093,  0.3013, -0.3251]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
second_rand_vector = torch.rand([1,7])
# Perform matrix multiplication
res = torch.matmul(random_vector, second_rand_vector.T)
res

tensor([[-1.3386],
        [ 0.8106],
        [ 0.8742],
        [-0.9921],
        [ 0.4892],
        [ 0.8283],
        [-0.1720]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [30]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
first = torch.rand([7,7])
second = torch.rand([1,7])

# Matrix multiply tensors
res = torch.matmul(X, Y.T)
res, res.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [7]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [27]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
first_tensor = torch.rand([2,3]).to(device)
second_tensor = torch.rand([2,3]).to(device)
first_tensor, second_tensor


Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [28]:
# Perform matmul on tensor_A and tensor_B
result_tensor = first_tensor @ second_tensor.T
result_tensor, result_tensor.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [12]:
# Find max
max = torch.max(result_tensor)
# Find min
min = torch.min(result_tensor)
max, min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [13]:
# Find arg max
max_arg = torch.argmax(result_tensor)

# Find arg min
min_arg = torch.argmin(result_tensor)
max_arg, min_arg

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [24]:
# Set seed
torch.manual_seed(1234)

# Create random tensor
first_tensor = torch.rand([1, 1, 1, 10]).to(device)
first_tensor
# Remove single dimensions
first_tensor_rem = first_tensor.view(10)

# Print out tensors and their shapes
print(first_tensor, first_tensor.shape)
print(first_tensor_rem, first_tensor_rem.shape)

tensor([[[[0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518, 0.4681,
           0.6738, 0.3315]]]], device='cuda:0') torch.Size([1, 1, 1, 10])
tensor([0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518, 0.4681, 0.6738,
        0.3315], device='cuda:0') torch.Size([10])
