In [1]:
import numpy as np
import tensorflow as tf

1.Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

2.Find the shape, rank and size of the tensors you created in 1.

3.Create two tensors containing random values between 0 and 1 with shape [5, 300].

4.Multiply the two tensors you created in 3 using matrix multiplication.

5.Multiply the two tensors you created in 3 using dot product.

6.Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

7.Find the min and max values of the tensor you created in 6.

8.Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

9.Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

10.One-hot encode the tensor you created in 9.

**По русски**

1.Создайте вектор, скаляр, матрицу и тензор со значениями по вашему выбору, используя tf.constant().

2.Найдите форму, ранг и размер тензоров, которые вы создали в 1.

3.Создайте два тензора, содержащих случайные значения от 0 до 1, с помощью shape [5, 300].

4.Умножьте два тензора, которые вы создали в 3, используя матричное умножение.

5.Умножьте два тензора, которые вы создали в 3, используя скалярное произведение.

6.Создайте тензор со случайными значениями от 0 до 1 с помощью shape [224, 224, 3].

7.Найдите минимальное и максимальное значения тензора, созданного вами в разделе 6.

8.Создайте тензор со случайными значениями формы [1, 224, 224, 3], затем сожмите его, чтобы изменить форму на [224, 224, 3].

9.Создайте тензор с помощью shape [10], используя выбранные вами значения, затем найдите индекс, который имеет максимальное значение.

10.Однократно закодируйте тензор, созданный в 9.


In [2]:
#Создайте вектор, скаляр, матрицу и тензор со значениями по вашему выбору, используя tf.constant().
vect = tf.constant([ 100, 200, 300])
scalarr = tf.constant(42)
Matrixx = tf.constant([[4, 5], [40, 50]])
tensorr = tf.constant([
    [[4, 5], [40, 50]],
    [[3, 1], [43, 52]],
    [[6, 2], [10, 40]]
    ])
vect, scalarr, Matrixx, tensorr

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([100, 200, 300], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=42>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 4,  5],
        [40, 50]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
 array([[[ 4,  5],
         [40, 50]],
 
        [[ 3,  1],
         [43, 52]],
 
        [[ 6,  2],
         [10, 40]]], dtype=int32)>)

In [14]:
#Найдите форму, ранг и размер тензоров, которые вы создали в 1.
@tf.function
def tf_size_func(tensorr):
  print("Shape ", tensorr.shape)
  print("Rank ", tensorr.ndim)
  print("Size ", tf.size(tensorr))
  print("|||||||||||||||||||||||||||||||||")

tf_size_func(vect)
tf_size_func(scalarr)
tf_size_func(Matrixx)
tf_size_func(tensorr)


Shape  (3,)
Rank  1
Size  Tensor("Size:0", shape=(), dtype=int32)
|||||||||||||||||||||||||||||||||
Shape  ()
Rank  0
Size  Tensor("Size:0", shape=(), dtype=int32)
|||||||||||||||||||||||||||||||||
Shape  (2, 2)
Rank  2
Size  Tensor("Size:0", shape=(), dtype=int32)
|||||||||||||||||||||||||||||||||
Shape  (3, 2, 2)
Rank  3
Size  Tensor("Size:0", shape=(), dtype=int32)
|||||||||||||||||||||||||||||||||


In [16]:
tf.size(tensorr)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [22]:
#Создайте два тензора, содержащих случайные значения от 0 до 1, с помощью shape [5, 300].
tensor_1 = tf.random.uniform(shape=[5, 300])
tensor_2 = tf.random.uniform(shape=[5, 300])
# Print the tensors
print("Tensor 1:")
print(tensor_1)
print("Tensor 2:")
print(tensor_2)

Tensor 1:
tf.Tensor(
[[0.97486687 0.47253096 0.35053384 ... 0.205114   0.42245865 0.08386374]
 [0.15189898 0.04189146 0.41002774 ... 0.9708804  0.7610245  0.5046545 ]
 [0.32073247 0.92557037 0.7600863  ... 0.85231006 0.05794728 0.1785649 ]
 [0.58402395 0.34574556 0.57753074 ... 0.53359735 0.01951432 0.6727593 ]
 [0.46317565 0.36298084 0.08565629 ... 0.03424335 0.55606127 0.3693087 ]], shape=(5, 300), dtype=float32)
Tensor 2:
tf.Tensor(
[[0.50200176 0.08285987 0.4995396  ... 0.13214481 0.6756704  0.7225462 ]
 [0.24390125 0.6954595  0.8069047  ... 0.21964216 0.14218926 0.65961945]
 [0.7453265  0.4024769  0.9214468  ... 0.45509744 0.8669199  0.4523896 ]
 [0.6340474  0.53341806 0.19627929 ... 0.54145217 0.8488982  0.39747846]
 [0.27994978 0.7474773  0.5301225  ... 0.8831285  0.18751848 0.72027886]], shape=(5, 300), dtype=float32)


In [23]:
#Умножьте два тензора, которые вы создали в 3, используя матричное умножение.
tf.matmul(tf.transpose(tensor_1), tensor_2)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[1.2654485 , 0.9732466 , 1.2652622 , ..., 1.0334163 , 1.5409672 ,
        1.5154306 ],
       [1.2581164 , 0.8965552 , 1.3830012 , ..., 1.0006318 , 1.4891955 ,
        1.1866502 ],
       [1.2326486 , 0.9922115 , 1.3651036 , ..., 0.8706447 , 1.4604077 ,
        1.1588467 ],
       ...,
       [1.3229283 , 1.3454654 , 1.7941161 , ..., 0.94739383, 1.4749137 ,
        1.4109504 ],
       [0.60892165, 1.0136415 , 1.1771152 , ..., 0.7509901 , 0.5647254 ,
        1.2417228 ],
       [0.82822394, 1.0646958 , 0.941467  , ..., 0.89360404, 0.9235785 ,
        1.0076689 ]], dtype=float32)>

In [24]:
#Умножьте два тензора, которые вы создали в 3, используя скалярное произведение.
tf.tensordot(tf.transpose(tensor_1), tensor_2, axes=1)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[1.2654485 , 0.9732466 , 1.2652622 , ..., 1.0334163 , 1.5409672 ,
        1.5154306 ],
       [1.2581164 , 0.8965552 , 1.3830012 , ..., 1.0006318 , 1.4891955 ,
        1.1866502 ],
       [1.2326486 , 0.9922115 , 1.3651036 , ..., 0.8706447 , 1.4604077 ,
        1.1588467 ],
       ...,
       [1.3229283 , 1.3454654 , 1.7941161 , ..., 0.94739383, 1.4749137 ,
        1.4109504 ],
       [0.60892165, 1.0136415 , 1.1771152 , ..., 0.7509901 , 0.5647254 ,
        1.2417228 ],
       [0.82822394, 1.0646958 , 0.941467  , ..., 0.89360404, 0.9235785 ,
        1.0076689 ]], dtype=float32)>

In [25]:
#Создайте тензор со случайными значениями от 0 до 1 с помощью shape [224, 224, 3].
tensor_3 = tf.random.uniform(shape=[224, 224, 3])
tensor_3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.30507278, 0.39879024, 0.45397842],
        [0.18319583, 0.7037786 , 0.61203575],
        [0.26799285, 0.15144837, 0.32408035],
        ...,
        [0.16176736, 0.59829605, 0.9257326 ],
        [0.00523579, 0.17546737, 0.09597838],
        [0.4818827 , 0.66880786, 0.44316423]],

       [[0.03622007, 0.9239379 , 0.8809372 ],
        [0.17869842, 0.6283163 , 0.87926173],
        [0.56659424, 0.3434317 , 0.0799433 ],
        ...,
        [0.19336593, 0.6009593 , 0.03811741],
        [0.8796841 , 0.81298935, 0.96156013],
        [0.15941179, 0.10108876, 0.9900522 ]],

       [[0.60668266, 0.42996418, 0.42994332],
        [0.9066616 , 0.07588601, 0.680935  ],
        [0.10908878, 0.8449414 , 0.51583874],
        ...,
        [0.62076735, 0.66354203, 0.60255396],
        [0.1101768 , 0.72789896, 0.8501047 ],
        [0.2118305 , 0.52716255, 0.7963618 ]],

       ...,

       [[0.81245375, 0.8636589 , 0.96004903],
        [0.77

In [27]:
#Найдите минимальное и максимальное значения тензора, созданного вами в разделе 6.
print("min = ", tf.reduce_min(tensor_3).numpy())
print("max = ", tf.reduce_max(tensor_3).numpy())

min =  2.3841858e-07
max =  0.9999987


In [28]:
#Создайте тензор со случайными значениями формы [1, 224, 224, 3], затем сожмите его, чтобы изменить форму на [224, 224, 3].
tensor_4 = tf.random.uniform(shape=[1, 224, 224, 3])
tensor_4

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.06229949, 0.17042959, 0.30270278],
         [0.67062247, 0.14383471, 0.17306316],
         [0.18875253, 0.01996434, 0.7104311 ],
         ...,
         [0.35744715, 0.4559884 , 0.9445863 ],
         [0.23912859, 0.94460475, 0.14034414],
         [0.79871583, 0.25034213, 0.35201347]],

        [[0.8262193 , 0.6420829 , 0.5722946 ],
         [0.5228077 , 0.60801303, 0.48517692],
         [0.6145848 , 0.23251784, 0.39085364],
         ...,
         [0.58425915, 0.45898235, 0.13564944],
         [0.61929715, 0.56146526, 0.8760079 ],
         [0.4528123 , 0.57581353, 0.33796835]],

        [[0.5224595 , 0.0763247 , 0.85511434],
         [0.42226183, 0.8272579 , 0.4956293 ],
         [0.45642197, 0.43537366, 0.36641347],
         ...,
         [0.03444362, 0.8817978 , 0.41844058],
         [0.1262343 , 0.10601711, 0.28059494],
         [0.4182757 , 0.00265074, 0.14554584]],

        ...,

        [[0.871346  , 0.18902385, 

In [29]:
tensor_4_squeezed = tf.squeeze(tensor_4)
tensor_4_squeezed

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.06229949, 0.17042959, 0.30270278],
        [0.67062247, 0.14383471, 0.17306316],
        [0.18875253, 0.01996434, 0.7104311 ],
        ...,
        [0.35744715, 0.4559884 , 0.9445863 ],
        [0.23912859, 0.94460475, 0.14034414],
        [0.79871583, 0.25034213, 0.35201347]],

       [[0.8262193 , 0.6420829 , 0.5722946 ],
        [0.5228077 , 0.60801303, 0.48517692],
        [0.6145848 , 0.23251784, 0.39085364],
        ...,
        [0.58425915, 0.45898235, 0.13564944],
        [0.61929715, 0.56146526, 0.8760079 ],
        [0.4528123 , 0.57581353, 0.33796835]],

       [[0.5224595 , 0.0763247 , 0.85511434],
        [0.42226183, 0.8272579 , 0.4956293 ],
        [0.45642197, 0.43537366, 0.36641347],
        ...,
        [0.03444362, 0.8817978 , 0.41844058],
        [0.1262343 , 0.10601711, 0.28059494],
        [0.4182757 , 0.00265074, 0.14554584]],

       ...,

       [[0.871346  , 0.18902385, 0.35569978],
        [0.20

In [38]:
#9.Создайте тензор с помощью shape [10], используя выбранные вами значения, затем найдите индекс, который имеет максимальное значение.
C = random_tensor = tf.random.uniform(shape=[10], minval=0, maxval=10, dtype=tf.int32)
print(tf.argmax(C).numpy())
C

9


<tf.Tensor: shape=(10,), dtype=int32, numpy=array([1, 0, 0, 7, 6, 7, 5, 5, 8, 9], dtype=int32)>

In [39]:
#10.One-hot encode the tensor you created in 9.
num_classes = len(tf.unique(C)[0])

# One-hot кодирование
C_one_hot = tf.one_hot(indices=C, depth=num_classes)

C_one_hot

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>